# <center> NumPy Arrays</center>

**NumPy arrays** are fixed size container of items that are more efficient than python list and tuples for data processing.
* They only store single data type.
* Array can be one dimensional or multi dimensional.
* Array element can be modified,but the array size cannot change.

In [2]:
#NumPy array function convert python list and tuples into numpy array

import numpy as np
price = [1,10,23,89,45,32,43,55,67,100,12] #Its a list

price_array =np.array(price)
price_array


array([  1,  10,  23,  89,  45,  32,  43,  55,  67, 100,  12])

**Array Properties** are:
* **ndim** - the number of dimension in the array.
* **shape** - the size of array of each dimension.
* **size** - the total number of elements in the array.
* **dtype** - the data type of the element in the array.

In [7]:
type(price)

list

In [6]:
type(price_array)

numpy.ndarray

In [11]:
print("ndim: ",price_array.ndim)
print("shape: ",price_array.shape)
print("size: ",price_array.size)
print("dtype: ",price_array.dtype)

ndim:  1
shape:  (11,)
size:  11
dtype:  int32


In [3]:
#converting nested list to a multi dimensional array.

sales =[[0,5,153,200],[0,182,2,4]]
sales_array =np.array(sales)

In [4]:
sales_array

array([[  0,   5, 153, 200],
       [  0, 182,   2,   4]])

In [5]:
print("ndim",sales_array.ndim)
print("shape",sales_array.shape)
print("size",sales_array.size)
print("dtype:",sales_array.dtype)


ndim 2
shape (2, 4)
size 8
dtype: int32


In [6]:
array_number = np.array(range(5))

In [7]:
array_number

array([0, 1, 2, 3, 4])

In [9]:
array_number+5

array([5, 6, 7, 8, 9])

In [10]:
array_2d =np.array([range(5),range(5,10)])

In [11]:
array_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
array_2d +10  #for the array its not neccessary to loop through the data

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
array_2d.size

10

In [14]:
array_2d.T # transpose the array

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [15]:
array_2d .ndim


2

## Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [16]:
my_list = [x * 10 for x in range(1, 11)]

In [17]:
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [18]:
array1 =np.array(my_list)

In [19]:
array1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [20]:
print("Number of dimension:",array1.ndim)
print("shape:",array1.shape)
print("No of elements:",array1.size)
print("Type of data:",array1.dtype)

Number of dimension: 1
shape: (10,)
No of elements: 10
Type of data: int32
