# <center>Random Number Generation</center>

We can create a random number array from the varienty of distribution using NumPy Functions and Methods(useful for sampling and simulation)
* default_rng
* random
* normal

In [2]:
from numpy.random import default_rng

rng=default_rng(12345)

random_number = rng.random(15)#generating 15 random number betweeb 0 to 1
random_number

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287,
       0.24824571, 0.94888115, 0.66723745, 0.09589794, 0.44183967])

In [4]:
mean,stdev = 6,2

random_normal =rng.normal(mean,stdev,size=20)

random_normal

array([7.08309366, 7.50387879, 4.68247936, 3.54265003, 6.51511554,
       6.62580584, 5.73837662, 8.53996624, 5.81407508, 5.86769822,
       3.78357107, 6.2719137 , 8.69415553, 6.12228804, 6.1418292 ,
       6.86730907, 6.55496732, 7.06050477, 7.07344194, 7.23670003])

# Assignment 2: Array Creation
 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the array using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [6]:
import numpy as np
array2 = np.arange(10)

In [7]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
array3 =np.linspace(10,100,10)

In [17]:
len(array3)

10

In [18]:
array3.reshape(5,2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [22]:
random_array =rng.random(9)

In [23]:
random_array.reshape(3,3)

array([[0.48276159, 0.21197904, 0.4956306 ],
       [0.24626133, 0.83848265, 0.18013059],
       [0.86215629, 0.17829944, 0.75053133]])