# <center> Array operations</center>

* [<span style='color:purple'>Assignment 4: Arithmetic Operations](#Assignment-4:-Arithmetic-Operations)
* [<span style='color:purple'>**Filtering and modifying array**](#Filtering-and-modifying-array)
* [<span style='color:purple'>**Where function**](#Where-function)
* [<span style='color:purple'>Assignment 5: Filtering Arrays](#Assignment-5:-Filtering-Arrays)
* [<span style='color:purple'>**Array aggregation method**](#Array-aggregation-method)
* [<span style='color:purple'>**Array functions**](#Array-functions)

In [3]:
import numpy as np

sales = [[1,2,3,4,5,10],[10,10,20,6,8,10]]

In [4]:
sales_array = np.array(sales)

In [10]:
add_number = sales_array + 2

In [11]:
add_number

array([[ 3,  4,  5,  6,  7, 12],
       [12, 12, 22,  8, 10, 12]])

In [7]:
quantity = sales_array[0]
price = sales_array[1]

In [12]:
total_array = quantity * price

In [13]:
total_array

array([ 10,  20,  60,  24,  40, 100])

In [14]:
rng = np.random.default_rng(1234)

In [19]:
random_number = rng.integers(1,100,20)

In [20]:
random_number

array([32, 79, 96, 95, 27, 56, 44, 26, 61, 89, 86, 64, 86, 52, 67, 95, 66,
        5, 73, 74], dtype=int64)

In [21]:
random_number + 2

array([34, 81, 98, 97, 29, 58, 46, 28, 63, 91, 88, 66, 88, 54, 69, 97, 68,
        7, 75, 76], dtype=int64)

In [22]:
random_2d = random_number.reshape(2,10)

In [23]:
random_2d 

array([[32, 79, 96, 95, 27, 56, 44, 26, 61, 89],
       [86, 64, 86, 52, 67, 95, 66,  5, 73, 74]], dtype=int64)

In [24]:
first_row =random_2d[0]
second_row=random_2d[1]

In [25]:
new_array = first_row * second_row

In [26]:
new_array

array([2752, 5056, 8256, 4940, 1809, 5320, 2904,  130, 4453, 6586],
      dtype=int64)

In [27]:
new_array.sum()

42206

## Assignment 4: Arithmetic Operations


They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array  and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [28]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])


In [29]:
total = prices+5

In [30]:
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [49]:
discount_pct =random_2d[0,:6]

In [50]:
discount_pct

array([32, 79, 96, 95, 27, 56], dtype=int64)

In [51]:
pct_owed =discount_pct - 1

In [52]:
pct_owed

array([31, 78, 95, 94, 26, 55], dtype=int64)

In [53]:
final_amount =total * pct_owed

In [56]:
final_amount.round(1)

array([ 340.7,  935.2, 2611.5, 9869.1,  259.7, 3024.5])

## Filtering and modifying array

In [5]:
import numpy as np

In [6]:
sales =[[10,11,12,34,0],[11,23,0,4,6]]

In [7]:
sales_array =np.array(sales)

In [8]:
sales_array

array([[10, 11, 12, 34,  0],
       [11, 23,  0,  4,  6]])

In [9]:
sales_array != 0

array([[ True,  True,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [10]:
sales_array[(sales_array > 5) & (sales_array <30)]

array([10, 11, 12, 11, 23,  6])

In [11]:
mask =(sales_array>10) & (sales_array<35)

In [12]:
sales_array[mask]

array([11, 12, 34, 11, 23])

In [13]:
sales_array

array([[10, 11, 12, 34,  0],
       [11, 23,  0,  4,  6]])

In [15]:
sales_elements= sales_array[1]

In [16]:
#filtering the array based on the value in other array

sales_elements

array([11, 23,  0,  4,  6])

In [17]:
product_element =np.array(['fruits','vegetables','cereals','diary','egg'])

In [18]:
product_element

array(['fruits', 'vegetables', 'cereals', 'diary', 'egg'], dtype='<U10')

In [20]:
product_element[sales_elements>0]

array(['fruits', 'vegetables', 'diary', 'egg'], dtype='<U10')

In [21]:
#return true if the number is even 

number_array =np.arange(20)

In [22]:
number_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
number_array % 2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [25]:
number_array[number_array%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Where function

where() function perform logical test and return a given value if the test is true or another if the test is false.

In [28]:
inventory_array=np.array([12,102,12,0,0])
inventory_array

array([ 12, 102,  12,   0,   0])

In [27]:
product_element

array(['fruits', 'vegetables', 'cereals', 'diary', 'egg'], dtype='<U10')

In [29]:
np.where(inventory_array>0,"in stock","out of stock")

array(['in stock', 'in stock', 'in stock', 'out of stock', 'out of stock'],
      dtype='<U12')

In [31]:
np.where(inventory_array>0,product_element,'out of stock')

array(['fruits', 'vegetables', 'cereals', 'out of stock', 'out of stock'],
      dtype='<U12')

##  Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [33]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [36]:
price_array = np.array([12,24,35,24,20,33])

In [39]:
# filter the product array those with prices greater than 25
products[(price_array>25)]

array(['mustard', 'gourmet ice cream'], dtype='<U17')

In [40]:
fancy_feast_special = products[(price_array >25) | (products =='cola')]

In [41]:
fancy_feast_special

array(['mustard', 'cola', 'gourmet ice cream'], dtype='<U17')

In [42]:
shipping_cost_array =np.where(price_array>20,0,5)

In [43]:
shipping_cost_array

array([5, 0, 0, 0, 5, 0])

In [14]:
sales_array

array([[10, 11, 12, 34,  0],
       [11, 23,  0,  4,  6]])

## Array aggregation method

In [15]:
sales_array.sum()

111

In [16]:
sales_array.min()

0

In [17]:
sales_array.max()

34

In [18]:
sales_array.mean()

11.1

In [22]:
sales_array

array([[10, 11, 12, 34,  0],
       [11, 23,  0,  4,  6]])

In [20]:
sales_array.sum(axis = 0)#collapse the row and perform sum 
                        #operation column wise

array([21, 34, 12, 38,  6])

In [21]:
sales_array.sum(axis=1)#collapse the column and perform sum 
                        #operation row wise

array([67, 44])

In [39]:
rng =np.random.default_rng(612)

In [41]:
price_array =rng.integers(1,100,10)

In [42]:
price_array

array([69, 16, 49, 31, 27, 64, 96, 23, 41, 52], dtype=int64)

In [46]:
price_array1 = price_array.reshape(2,5)

In [ ]:
price_array1

In [49]:
total = sales_array * price_array1
total

array([[ 690,  176,  588, 1054,    0],
       [ 704, 2208,    0,  164,  312]], dtype=int64)

In [50]:
total.min()

0

In [51]:
total.max()

2208

In [52]:
total.sum(axis=0)

array([1394, 2384,  588, 1218,  312], dtype=int64)

In [53]:
total.sum(axis=1)

array([2508, 3388], dtype=int64)

## Array functions

In [54]:
cost =np.array([2.6,7.2,6.92,3.88,0.78,2.67,8.87,0.23,5.23,6.3])

In [55]:
len(cost)

10

In [56]:
inventory =np.array([79,22,20,48,8,76,12,16,5,64])

In [57]:
len(inventory)

10

In [59]:
product_price =cost*inventory

In [60]:
product_price

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [61]:
reshape_product=product_price.reshape(5,2)

In [62]:
reshape_product

array([[205.4 , 158.4 ],
       [138.4 , 186.24],
       [  6.24, 202.92],
       [106.44,   3.68],
       [ 26.15, 403.2 ]])

In [63]:
np.median(reshape_product)

148.4

In [69]:
np.mean(reshape_product).round(2)

143.71

In [68]:
np.percentile(reshape_product,90).round(2)

225.18

In [70]:
np.median(reshape_product,axis=0)

array([106.44, 186.24])

In [71]:
np.median(reshape_product,axis=1)

array([181.9  , 162.32 , 104.58 ,  55.06 , 214.675])

In [72]:
np.unique(reshape_product) #unique is used for categorical data

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [73]:
np.sqrt(reshape_product)

array([[14.33178286, 12.58570618],
       [11.76435294, 13.64697769],
       [ 2.4979992 , 14.24499912],
       [10.3169763 ,  1.91833261],
       [ 5.11370707, 20.07984064]])

In [74]:
reshape_product

array([[205.4 , 158.4 ],
       [138.4 , 186.24],
       [  6.24, 202.92],
       [106.44,   3.68],
       [ 26.15, 403.2 ]])

In [76]:
reshape_product.sort()#by default axis =1 
reshape_product

array([[158.4 , 205.4 ],
       [138.4 , 186.24],
       [  6.24, 202.92],
       [  3.68, 106.44],
       [ 26.15, 403.2 ]])

In [77]:
reshape_product.sort(axis=0)

In [78]:
reshape_product

array([[  3.68, 106.44],
       [  6.24, 186.24],
       [ 26.15, 202.92],
       [138.4 , 205.4 ],
       [158.4 , 403.2 ]])

## Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [79]:
prices1 = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices1

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [80]:
#top 3 highest priced items

prices1.sort() #sort the array from ascending to descending

In [81]:
prices1

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [94]:
reverse_price =prices1[::-1]# reverse the sorted array

In [96]:
print("top 3 highest priced items",reverse_price[:3])

top 3 highest priced items [99.99 49.99 22.49]


In [98]:
top3 =reverse_price[:3]

In [99]:
top3

array([99.99, 49.99, 22.49])

In [104]:
print("minimum",top3.min())
print("maximum",top3.max())
print("mean",top3.mean())
print("median",np.median(top3))

minimum 22.49
maximum 99.99
mean 57.49
median 49.99


In [105]:
prices1

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [107]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [108]:
price_tiers

array(['budget', 'budget', 'mid-tier', 'luxury', 'mid-tier', 'luxury'],
      dtype='<U8')

In [109]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

### Note:
<span style ="color:purple">1.Numpy forms the **foundation for Pandas**<br>
    2.Numpy arrays are **more efficient** than base python list and tuples<br>
    3.Array operation let you **aggregate,filter and sort** data</span>